
cd classes

scala fos.SimplyTyped "inl x as Nat"
scala fos.SimplyTyped "inr x as Bool"
scala fos.SimplyTyped "case pred 0 of inl x1 => \\x:Nat.x | inr x2 => \\x:Bool.x"
scala fos.SimplyTyped "\\x:Bool->Nat*Bool+Nat->Bool.x"

scala fos.SimplyTyped "(\\x:Nat. inl x as Nat + Bool * Nat) 0"
scala fos.SimplyTyped "(\\x:Bool. inl x as Bool + Bool * Nat) false"

scala fos.SimplyTyped "(\\x:Nat. inr x as (Bool * Nat) + Nat) 0"
scala fos.SimplyTyped "(\\x:Bool. inr x as (Bool * Nat) + Bool) false"

scala fos.SimplyTyped "case inl 0 as Nat+Bool of inl x1 => if true then pred false else false | inr x2 => false"
scala fos.SimplyTyped "case inl 0 as Nat+Bool of inl x1 => iszero x1 | inr x2 => false"
scala fos.SimplyTyped "case inr false as Nat+Bool of inl x1 => false | inr x2 => if x2 then false else true"


scala fos.SimplyTyped "case inl 0 as Nat+Bool of inl x => (\\x:Nat . iszero succ x) 5 | inr x => false"
scala fos.SimplyTyped "(\\x:Nat. (\\x:Nat . case inl 0 as Nat+Nat of inl x => x | inr x => 1) 2) 3"
scala fos.SimplyTyped "(\\x:Nat. case (inl x as Nat + Bool) of inl x => succ succ x | inr x => if x then 0 else 1) 0"

scala fos.SimplyTyped "fix \\x:Bool. iszero ((\\x:Nat. pred x) 5)"

# Hard test: iseven from the course
scala fos.SimplyTyped "(fix (\\ie:Nat->Bool.\\x:Nat. if iszero x then true else if iszero (pred x) then false else ie (pred (pred x)))) 7"
scala fos.SimplyTyped "(fix (\\ie:Nat->Bool.\\x:Nat. if iszero x then true else if iszero (pred x) then false else ie (pred (pred x)))) 10"
scala fos.SimplyTyped "(fix (\\ie:Nat->Bool.\\x:Nat. if iszero x then true else if iszero (pred x) then false else ie (pred (pred x)))) 0"
scala fos.SimplyTyped "(fix (\\ie:Nat->Bool.\\x:Nat. if iszero x then true else if iszero (pred x) then false else ie (pred (pred x)))) 1"

scala fos.SimplyTyped "(\x:Nat.if (iszero x) then 0 else if (iszero (pred x)) then 1 else succ 0) (pred (pred 2))"
scala fos.SimplyTyped "let x:Nat = 0 in x"
scala fos.SimplyTyped "letrec plus:Nat->Nat = \\x:Nat. if iszero x then 1 else succ (plus (pred x)) in plus 2"
scala fos.SimplyTyped "letrec iseven:Nat->Bool = \\x:Nat. if iszero x then true else if iszero (pred x) then false else iseven (pred (pred x)) in iseven 7"

exit

#scala fos.SimplyTyped "(\\x:Bool. case (inr x as Nat + Bool) of inl x => succ succ x | inr x => if x then 0 else 1) false"
#scala fos.SimplyTyped "(\\x:Nat. case (inl x as Nat + Bool) of inl x => inl pred pred pred x as Nat + Nat | inr x => inr if x then 0 else 1 as Nat + Nat) 2"
#scala fos.SimplyTyped "(\\x:Bool. case (inr x as Nat + Bool) of inl x => inl pred pred pred x as Nat + Nat | inr x => inr if x then 0 else 1 as Nat + Nat) false"

#scala fos.SimplyTyped "fst ((\\x:Nat . {pred x, succ x}) 3)"
#scala fos.SimplyTyped "let x: Nat = true in x "
#scala fos.SimplyTyped "let x: Nat = pred pred 0 in x"
#scala fos.SimplyTyped "let x: Nat = true in x"

# Hard test
scala fos.SimplyTyped "if snd {false, true} then (\\x:Nat*Nat->Bool . x {1, 1}) (\\x:Nat*Nat. iszero fst x) else true"

scala fos.SimplyTyped "1 2 3"
scala fos.SimplyTyped "if true then fst {1, false} else snd {true, 0}"
scala fos.SimplyTyped "if true then fst {1, false} else snd {1, false}"

scala fos.SimplyTyped "true"
scala fos.SimplyTyped "false"
scala fos.SimplyTyped "5"
scala fos.SimplyTyped "succ 0"
scala fos.SimplyTyped "pred 0"
scala fos.SimplyTyped "iszero 0"
scala fos.SimplyTyped "pred 4"
scala fos.SimplyTyped "if true then succ pred 0 else 0"
scala fos.SimplyTyped "if if true then false else false then true else false"
scala fos.SimplyTyped "\\x: Bool . y"
scala fos.SimplyTyped "\\x: Bool -> Nat -> Bool * Nat . y"
scala fos.SimplyTyped "\\x: Nat * Nat -> Bool . y"
scala fos.SimplyTyped "\\x: Bool -> Nat * (Nat -> Nat) . y"
scala fos.SimplyTyped "\\x: (Nat * Nat) . y"
scala fos.SimplyTyped "x y z"
scala fos.SimplyTyped "fst snd {x,{y,z}} "
scala fos.SimplyTyped "z let x : Nat * Nat = \\x: Nat. y in x x "
scala fos.SimplyTyped "let x : Nat = succ pred 0 in iszero x"
scala fos.SimplyTyped "succ pred 1"
scala fos.SimplyTyped "pred true"
scala fos.SimplyTyped "succ pred pred true"
scala fos.SimplyTyped "iszero false"
scala fos.SimplyTyped "if pred true then 1 else 2"
scala fos.SimplyTyped "if true then 1 else false"
scala fos.SimplyTyped "if pred succ pred pred 0 then 1 else 5"
scala fos.SimplyTyped "if iszero 3 then 2 else 1"
scala fos.SimplyTyped "\\x:Nat . if false then true else false "
scala fos.SimplyTyped "\\x:Nat . if false then pred true else false "
scala fos.SimplyTyped "\\x:Nat . if iszero 5 then \\x: Nat. if true then false else iszero pred 6  else \\x : Nat. false "
scala fos.SimplyTyped "\\x:Nat . x"
scala fos.SimplyTyped "x"
scala fos.SimplyTyped "\\x:Nat. (\\x:Bool. x)"
scala fos.SimplyTyped "\\x:Nat. \\x:Nat. x iszero x"
scala fos.SimplyTyped "\\x:Nat. \\y:Bool->Nat. y iszero x"
scala fos.SimplyTyped "let x : Nat = x in let y:Bool = y in y"
scala fos.SimplyTyped "(\\y:Nat . (z x))"
scala fos.SimplyTyped "\\x:Nat . (\\y:Nat . ((x y) x))"
scala fos.SimplyTyped "x y"
scala fos.SimplyTyped "\\x:Nat . \\y:Nat . z y"
scala fos.SimplyTyped "(\\x:Nat . x) ((\\x:Nat . x) (\\z:Nat. (\\x:Nat . x) z))"
scala fos.SimplyTyped "\\t:Bool . \\f:Bool . t"
scala fos.SimplyTyped "\\t:Bool . \\f:Bool . f"
scala fos.SimplyTyped "\\l:Bool . \\m:Bool . \\n:Bool . l m n"
scala fos.SimplyTyped "let n:Nat = ((\\y:Nat . succ y) 1) in n"
scala fos.SimplyTyped "{true, {false, 5}}"
scala fos.SimplyTyped "fst {true, 0}"
scala fos.SimplyTyped "snd {true, \\x:Nat. iszero x}"
scala fos.SimplyTyped "(\\y:Nat. y) true"
scala fos.SimplyTyped "(\\x:Bool. (\\y:Nat . y) x) true"
scala fos.SimplyTyped "let x : Bool = iszero 4 in (\\y:Bool . y) x"
scala fos.SimplyTyped "iszero 0"
scala fos.SimplyTyped "iszero true"
scala fos.SimplyTyped "iszero succ pred succ pred 0"
scala fos.SimplyTyped "iszero pred 0"
scala fos.SimplyTyped "if false then false else if false then true else iszero succ pred succ pred pred 0"
scala fos.SimplyTyped "if false then false else if false then true else iszero true"
scala fos.SimplyTyped "(\\x:Nat->Nat.x) (\\x:Nat. (\\x:Nat.x) x)"
scala fos.SimplyTyped "if true then (\\x:Bool. (\\x:Bool.x) x) true else (\\y:Bool.y) false"
scala fos.SimplyTyped "(\\y:Bool.((\\x:Bool.(\\y:Bool.x)) y)) true"
scala fos.SimplyTyped "(\\y:Bool.((\\x:Bool.(\\y:Bool.y)) y)) true"
scala fos.SimplyTyped "((\\x:Nat.iszero x) succ 0)"
scala fos.SimplyTyped "let x : Nat = 2 in let x : Nat = succ x in succ x "
scala fos.SimplyTyped "let x : Nat = 2 in let x : Nat = pred x in succ x"
scala fos.SimplyTyped "{if iszero 0 then 1 else 0, (\\x:Nat. succ succ x) 0}"
scala fos.SimplyTyped "fst {if iszero 0 then 1 else 0, (\\x:Nat. succ succ x) 0}"
scala fos.SimplyTyped "snd {if iszero 0 then 1 else 0, (\\x:Nat. succ succ x) 0}"
scala fos.SimplyTyped "fst {pred 4, if true then false else false}"
scala fos.SimplyTyped "snd {pred 4, if true then false else false}"
scala fos.SimplyTyped "(\\x:Nat*Nat. snd x) {pred 4, pred 5}"

